-- Project database schema
-- Keep this file in sync with the actual database.

-- ============================================================================
-- GROOVY DATABASE SCHEMA
-- ============================================================================
-- Status: No database currently used
-- This is a client-side application with no backend or database.
-- All data is stored in browser memory and lost on refresh.
--
-- Future considerations:
-- - User accounts (Firebase Auth or similar)
-- - Pattern storage (Firebase Firestore, PostgreSQL, or MongoDB)
-- - Pattern sharing (public/private patterns)
-- - User preferences (tempo, swing, favorite patterns)
-- ============================================================================

-- ============================================================================
-- FUTURE SCHEMA (If Database Added)
-- ============================================================================

-- Users table (if user accounts added)
-- CREATE TABLE users (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   email VARCHAR(255) UNIQUE NOT NULL,
--   username VARCHAR(50) UNIQUE NOT NULL,
--   display_name VARCHAR(100),
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   last_login TIMESTAMP,
--   is_active BOOLEAN DEFAULT TRUE
-- );

-- Patterns table (if pattern storage added)
-- CREATE TABLE patterns (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   user_id UUID REFERENCES users(id) ON DELETE CASCADE,
--   name VARCHAR(100) NOT NULL,
--   description TEXT,
--   tempo INTEGER NOT NULL CHECK (tempo >= 40 AND tempo <= 240),
--   swing INTEGER NOT NULL CHECK (swing >= 0 AND swing <= 100),
--   time_signature_beats INTEGER NOT NULL DEFAULT 4,
--   time_signature_note_value INTEGER NOT NULL DEFAULT 4,
--   division INTEGER NOT NULL DEFAULT 16,
--   notes JSONB NOT NULL, -- { hihat: [true, false, ...], snare: [...], kick: [...] }
--   is_public BOOLEAN DEFAULT FALSE,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- Pattern tags (if categorization added)
-- CREATE TABLE tags (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   name VARCHAR(50) UNIQUE NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- Pattern-Tag relationship (many-to-many)
-- CREATE TABLE pattern_tags (
--   pattern_id UUID REFERENCES patterns(id) ON DELETE CASCADE,
--   tag_id UUID REFERENCES tags(id) ON DELETE CASCADE,
--   PRIMARY KEY (pattern_id, tag_id)
-- );

-- User preferences (if settings storage added)
-- CREATE TABLE user_preferences (
--   user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
--   default_tempo INTEGER DEFAULT 120,
--   default_swing INTEGER DEFAULT 0,
--   theme VARCHAR(20) DEFAULT 'dark', -- 'light' or 'dark'
--   auto_save BOOLEAN DEFAULT TRUE,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- Indexes (for performance)
-- CREATE INDEX idx_patterns_user_id ON patterns(user_id);
-- CREATE INDEX idx_patterns_is_public ON patterns(is_public);
-- CREATE INDEX idx_patterns_created_at ON patterns(created_at DESC);
-- CREATE INDEX idx_pattern_tags_pattern_id ON pattern_tags(pattern_id);
-- CREATE INDEX idx_pattern_tags_tag_id ON pattern_tags(tag_id);

-- ============================================================================
-- NOTES
-- ============================================================================
-- - No database is currently used in the project
-- - This schema is for future reference if/when a database is added
-- - Consider using Firebase Firestore for simpler setup (NoSQL)
-- - Or PostgreSQL for relational data with complex queries
-- - Or MongoDB for flexible schema and JSON storage
-- ============================================================================
